create_clock -period 10.000 -name sys_clk [get_ports clk]

set_load 5.000 [all_outputs]
set_property LOAD 5 [get_ports {imem_addr[0]}]
set_property LOAD 5 [get_ports {imem_addr[10]}]
set_property LOAD 5 [get_ports {imem_addr[11]}]
set_property LOAD 5 [get_ports {imem_addr[12]}]
set_property LOAD 5 [get_ports {imem_addr[13]}]
set_property LOAD 5 [get_ports {imem_addr[14]}]
set_property LOAD 5 [get_ports {imem_addr[15]}]
set_property LOAD 5 [get_ports {imem_addr[16]}]
set_property LOAD 5 [get_ports {imem_addr[17]}]
set_property LOAD 5 [get_ports {imem_addr[18]}]
set_property LOAD 5 [get_ports {imem_addr[19]}]
set_property LOAD 5 [get_ports {imem_addr[1]}]
set_property LOAD 5 [get_ports {imem_addr[20]}]
set_property LOAD 5 [get_ports {imem_addr[21]}]
set_property LOAD 5 [get_ports {imem_addr[22]}]
set_property LOAD 5 [get_ports {imem_addr[23]}]
set_property LOAD 5 [get_ports {imem_addr[24]}]
set_property LOAD 5 [get_ports {imem_addr[25]}]
set_property LOAD 5 [get_ports {imem_addr[26]}]
set_property LOAD 5 [get_ports {imem_addr[27]}]
set_property LOAD 5 [get_ports {imem_addr[28]}]
set_property LOAD 5 [get_ports {imem_addr[29]}]
set_property LOAD 5 [get_ports {imem_addr[2]}]
set_property LOAD 5 [get_ports {imem_addr[30]}]
set_property LOAD 5 [get_ports {imem_addr[31]}]
set_property LOAD 5 [get_ports {imem_addr[3]}]
set_property LOAD 5 [get_ports {imem_addr[4]}]
set_property LOAD 5 [get_ports {imem_addr[5]}]
set_property LOAD 5 [get_ports {imem_addr[6]}]
set_property LOAD 5 [get_ports {imem_addr[7]}]
set_property LOAD 5 [get_ports {imem_addr[8]}]
set_property LOAD 5 [get_ports {imem_addr[9]}]
set_property LOAD 5 [get_ports spi_cs_n]
set_property LOAD 5 [get_ports spi_mosi]
set_property LOAD 5 [get_ports spi_sclk]
